[bold]
family = "Cousine NFM"
style = "Bold"

[colors.primary]
background = "#000000"
foreground = "#c5c8c6"

[font]
style = "Regular"

[font.normal]
family = "Cousine NFM"

[italic]
family = "monospace"
size = 7.0
style = "Italic"

[scrolling]
history = 100000

[window]
opacity = 0.85
